Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2023-07, with the labels that each got.

#51 Make profiler work
  internal/e2e/go.mod
  internal/e2e/guest_test.go
  internal/e2e/plugin_perf_test.go
  internal/e2e/profiler/profiler.go
  scheduler/plugin/export_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/runtime.go
Labels: kind/bug, approved, size/M, cncf-cla: yes

#53 deps: updates to wazero 1.3.0
  internal/e2e/go.mod
  internal/e2e/go.sum
  scheduler/go.mod
  scheduler/go.sum
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#56 Remove kerthcet from approver
  OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, cncf-cla: yes

#57 Fix documenation error around preemption in RATIONALE.md
  RATIONALE.md
Labels: size/S, approved, kind/documentation, lgtm, cncf-cla: yes

#61 Run codec benchmarks in wasm
  Makefile
  internal/e2e/go.mod
  internal/e2e/guest/go.mod
  internal/e2e/guest/go.sum
  internal/e2e/guest/guest_test.go
  internal/e2e/scheduler/scheduler_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes, kind/cleanup

#59 Implement PreScore and change NodeNumberPlugin to use it
  RATIONALE.md
  examples/go.mod
  examples/go.sum
  examples/nodenumber/main.go
  examples/nodenumber/main.wasm
  examples/nodenumber/plugin/plugin.go
  examples/nodenumber/plugin/plugin_test.go
  guest/api/proto/proto.go
  guest/api/types.go
  guest/filter/filter.go
  guest/prefilter/prefilter.go
  guest/prescore/prescore.go
  guest/score/score.go
  guest/testdata/all/main.go
  guest/testdata/all/main.wasm
  guest/testdata/cyclestate/main.go
  guest/testdata/cyclestate/main.wasm
  guest/testdata/filter/main.go
  guest/testdata/filter/main.wasm
  guest/testdata/score/main.go
  guest/testdata/score/main.wasm
  internal/e2e/e2e.go
  internal/e2e/profiler/profiler.go
  internal/e2e/scheduler/scheduler_test.go
  scheduler/plugin/guest.go
  scheduler/plugin/host.go
  scheduler/plugin/mask.go
  scheduler/plugin/mask_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
  scheduler/test/testdata/error/panic_on_prescore.wasm
  scheduler/test/testdata/error/panic_on_prescore.wat
  scheduler/test/testdata/error/prescore_without_score.wasm
  scheduler/test/testdata/error/prescore_without_score.wat
  scheduler/test/testdata/test/prescore_from_global.wasm
  scheduler/test/testdata/test/prescore_from_global.wat
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XL

#63 feat: implement scheduler_perf
  .gitignore
  Makefile
  internal/e2e/go.mod
  internal/e2e/go.sum
  internal/e2e/scheduler_perf/README.md
  internal/e2e/scheduler_perf/config/performance-config.yaml
  internal/e2e/scheduler_perf/config/pod-default.yaml
  internal/e2e/scheduler_perf/config/sched-config-all-enabled.yaml
  internal/e2e/scheduler_perf/config/sched-config-extender-only.yaml
  internal/e2e/scheduler_perf/config/sched-config-plugin-only.yaml
  internal/e2e/scheduler_perf/config/sched-config-wasm-only.yaml
  internal/e2e/scheduler_perf/extender/nodenumber.go
  internal/e2e/scheduler_perf/nodenumber/plugin.go
  internal/e2e/scheduler_perf/scheduler_perf_test.go
  internal/e2e/scheduler_perf/util.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XXL

#66 guest: inlines host.GetConfig to config.Get
  examples/nodenumber/main.go
  examples/nodenumber/main.wasm
  examples/nodenumber/plugin/plugin.go
  guest/api/host.go
  guest/config/config.go
  guest/config/imports.go
  guest/config/imports_stub.go
  guest/config/internal/config.go
  guest/config/internal/config_test.go
  guest/internal/mem/mem.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#68 config: add support to file:// and http(s):// URIs
  internal/e2e/profiler/profiler.go
  internal/e2e/scheduler/scheduler_test.go
  scheduler/go.mod
  scheduler/plugin/config.go
  scheduler/plugin/http.go
  scheduler/plugin/http_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
Labels: kind/feature, approved, kind/api-change, lgtm, cncf-cla: yes, size/L
