Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2023-05, with the labels that each got.

#5 update(OWNERS): add reviewers
  OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#2 Add issue & PR template in github
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CLEANUP.md
  .github/ISSUE_TEMPLATE/ENHANCEMENT.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation, lgtm, cncf-cla: yes, size/L

#4 update(docs): update readme to explain what it is briefly
  CONTRIBUTING.md
  README.md
  RELEASE.md
Labels: approved, kind/documentation, lgtm, tide/merge-method-squash, size/M, cncf-cla: yes

#10 Fix tools.go not exist error
  Makefile
  kubernetes/proto/tools/tools.go
Labels: kind/bug, approved, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#18 feature: set up the scheduler with wasm plugin
  scheduler/cmd/scheduler/main.go
  scheduler/go.mod
  scheduler/go.sum
  scheduler/pkg/plugins/wasm/config.go
  scheduler/pkg/plugins/wasm/guest.go
  scheduler/pkg/plugins/wasm/host.go
  scheduler/pkg/plugins/wasm/mem.go
  scheduler/pkg/plugins/wasm/plugin.go
  scheduler/pkg/plugins/wasm/plugin_perf_test.go
  scheduler/pkg/plugins/wasm/plugin_test.go
  scheduler/pkg/plugins/wasm/runtime.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#20 add: add the copyright header
  example/main.go
  guest/api/status.go
  guest/api/types.go
  guest/filter.go
  guest/internal/imports/host.go
  guest/internal/imports/imports.go
  guest/internal/imports/imports_stub.go
  guest/internal/imports/mem.go
  kubernetes/proto/tools/tools.go
  scheduler/cmd/scheduler/main.go
  scheduler/pkg/plugins/wasm/config.go
  scheduler/pkg/plugins/wasm/guest.go
  scheduler/pkg/plugins/wasm/host.go
  scheduler/pkg/plugins/wasm/mem.go
  scheduler/pkg/plugins/wasm/plugin.go
  scheduler/pkg/plugins/wasm/plugin_perf_test.go
  scheduler/pkg/plugins/wasm/plugin_test.go
  scheduler/pkg/plugins/wasm/runtime.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L
