Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2023-06, with the labels that each got.

#24 Add profile make target
  .gitignore
  Makefile
  internal/e2e/go.mod
  internal/e2e/go.sum
  internal/e2e/plugin_perf_test.go
  internal/e2e/profiler/profiler.go
  scheduler/cmd/scheduler/main.go
  scheduler/go.mod
  scheduler/go.sum
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/testdata/testdata.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L

#21 feature: always assign the same instance to the same Pod
  scheduler/go.mod
  scheduler/go.sum
  scheduler/plugin/export_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/XL

#28 docs: adds RATIONALE.md with section on why TinyGo
  guest/RATIONALE.md
Labels: approved, kind/documentation, lgtm, tide/merge-method-squash, size/M, cncf-cla: yes

#25 Replace the default wasm garbage collector with nottinygc
  Makefile
  examples/filter-simple/go.mod
  examples/filter-simple/go.sum
  examples/filter-simple/main.wasm
  examples/noop/go.mod
  examples/noop/go.sum
  examples/noop/main.wasm
  guest/RATIONALE.md
  guest/filter.go
  guest/go.mod
  guest/go.sum
  internal/e2e/codec_perf_test.go
  internal/e2e/go.mod
  internal/e2e/plugin_perf_test.go
  internal/e2e/profiler/profiler.go
  scheduler/cmd/scheduler/main.go
  scheduler/plugin/guest.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
  scheduler/test/testdata/error/panic_on_filter.wasm
  scheduler/test/testdata/error/panic_on_filter.wat
  scheduler/test/testdata/error/panic_on_start.wasm
  scheduler/test/testdata/error/panic_on_start.wat
  scheduler/test/testdata/yaml/node.yaml
  scheduler/test/testdata/yaml/pod.yaml
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#31 extracts out pool and stubs plugin functions
  internal/e2e/profiler/profiler.go
  scheduler/cmd/scheduler/main.go
  scheduler/plugin/export_test.go
  scheduler/plugin/guest.go
  scheduler/plugin/host.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/pool.go
  scheduler/plugin/pool_test.go
  scheduler/test/testdata.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/XL

#30 ci: adds basic setup
  .github/workflows/commit.yaml
  .github/workflows/testdata.yaml
  Makefile
  examples/filter-simple/go.mod
  examples/noop/go.mod
  guest/filter.go
  guest/go.mod
  internal/e2e/plugin_perf_test.go
  kubernetes/proto/api/generated.pb.go
  kubernetes/proto/api/generated_vtproto.pb.go
  kubernetes/proto/go.mod
  kubernetes/proto/meta/generated.pb.go
  kubernetes/proto/meta/generated_vtproto.pb.go
  scheduler/test/testdata.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#32 makes guest API more similar to host
  Makefile
  examples/filter-simple/main.go
  examples/filter-simple/main.wasm
  examples/noop/main.go
  examples/noop/main.wasm
  guest/api/status.go
  guest/api/types.go
  guest/filter/filter.go
  guest/internal/imports/host.go
  guest/internal/imports/imports_stub.go
  guest/internal/imports/mem.go
  guest/internal/types/types.go
  internal/e2e/go.mod
  internal/e2e/profiler/profiler.go
  scheduler/plugin/guest.go
  scheduler/plugin/mem.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/runtime.go
  scheduler/test/testdata.go
  scheduler/test/testdata/error/not_plugin.wasm
  scheduler/test/testdata/error/not_plugin.wat
Labels: approved, kind/api-change, lgtm, cncf-cla: yes, kind/cleanup, size/L

#34 Reuse call stack when invoking filter
  scheduler/plugin/guest.go
Labels: size/S, approved, lgtm, tide/merge-method-squash, cncf-cla: yes

#36 deps: updates to TinyGo 0.28.1
  .github/workflows/testdata.yaml
  examples/filter-simple/main.wasm
  examples/score-simple/main.wasm
  guest/internal/imports/imports.go
  guest/testdata/noop/main.wasm
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#37 fix(host): remove lock from Score
  scheduler/plugin/plugin.go
Labels: approved, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#38 changes benchmarks in preparation of value caching
  Makefile
  guest/testdata/all-noop/main.go
  guest/testdata/all-noop/main.wasm
  guest/testdata/all/main.go
  guest/testdata/all/main.wasm
  guest/testdata/filter/main.go
  guest/testdata/filter/main.wasm
  guest/testdata/score/main.go
  guest/testdata/score/main.wasm
  internal/e2e/plugin_perf_test.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
  scheduler/test/testdata/test/all_noop.wasm
  scheduler/test/testdata/test/all_noop.wat
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#40 allocates less buffers when decoding multiple large protos
  examples/filter-simple/main.wasm
  examples/score-simple/main.wasm
  guest/internal/imports/host.go
  guest/internal/imports/mem.go
  guest/internal/types/types.go
  guest/testdata/all/main.wasm
  guest/testdata/filter/main.wasm
  guest/testdata/score/main.wasm
Labels: approved, lgtm, size/M, cncf-cla: yes, kind/cleanup

#39 Switches from UID to pointer for identifying cycle IDs
  internal/e2e/plugin_perf_test.go
  scheduler/plugin/export_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/pool.go
  scheduler/plugin/pool_test.go
Labels: kind/bug, approved, lgtm, cncf-cla: yes, size/XL

#41 Updates wazero to 1.2.1
  guest/internal/imports/mem.go
  internal/e2e/go.mod
  internal/e2e/go.sum
  scheduler/go.mod
  scheduler/go.sum
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#42 Changes guest index back to UID
  scheduler/go.mod
  scheduler/plugin/export_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/pool.go
  scheduler/plugin/pool_test.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#46 Add codefromthecrypt as an owner
  OWNERS
Labels: approved, kind/documentation, lgtm, size/XS, cncf-cla: yes

#45 Adds cyclestate.Pod to share unmarshalled result to all plugins
  Makefile
  examples/filter-simple/main.go
  examples/filter-simple/main.wasm
  examples/prefilter-simple/main.go
  examples/prefilter-simple/main.wasm
  examples/score-simple/main.go
  examples/score-simple/main.wasm
  guest/RATIONALE.md
  guest/filter/filter.go
  guest/filter/filter_exports.go
  guest/internal/cyclestate/cyclestate.go
  guest/internal/prefilter/cstring.go
  guest/internal/prefilter/cstring_test.go
  guest/internal/prefilter/imports.go
  guest/internal/prefilter/imports_stub.go
  guest/internal/prefilter/pod.go
  guest/internal/prefilter/prefilter_exports.go
  guest/internal/types/types.go
  guest/prefilter/prefilter.go
  guest/score/score.go
  guest/score/score_exports.go
  guest/testdata/all-noop/main.go
  guest/testdata/all-noop/main.wasm
  guest/testdata/all/main.go
  guest/testdata/all/main.wasm
  guest/testdata/filter/main.go
  guest/testdata/filter/main.wasm
  guest/testdata/go.mod
  guest/testdata/prefilter/main.go
  guest/testdata/prefilter/main.wasm
  guest/testdata/score/main.go
  guest/testdata/score/main.wasm
  internal/e2e/guest_test.go
  internal/e2e/plugin_perf_test.go
  scheduler/plugin/plugin_test.go
Labels: approved, lgtm, cncf-cla: yes, kind/cleanup, size/L

#47 chore: fix comments and make the preFilter function unexported
  scheduler/plugin/guest.go
  scheduler/plugin/plugin.go
Labels: approved, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#50 Implements cyclestate in guest
  Makefile
  RATIONALE.md
  examples/filter-simple/main.go
  examples/filter-simple/main.wasm
  examples/prefilter-simple/main.go
  examples/prefilter-simple/main.wasm
  examples/score-simple/main.go
  examples/score-simple/main.wasm
  guest/RATIONALE.md
  guest/api/types.go
  guest/filter/filter_exports.go
  guest/internal/cyclestate/cyclestate.go
  guest/internal/prefilter/pod.go
  guest/internal/prefilter/prefilter_exports.go
  guest/score/score_exports.go
  guest/testdata/all-noop/main.go
  guest/testdata/all-noop/main.wasm
  guest/testdata/all/main.go
  guest/testdata/all/main.wasm
  guest/testdata/cyclestate/main.go
  guest/testdata/cyclestate/main.wasm
  guest/testdata/filter/main.go
  guest/testdata/filter/main.wasm
  guest/testdata/prefilter/main.go
  guest/testdata/prefilter/main.wasm
  guest/testdata/score/main.go
  guest/testdata/score/main.wasm
  internal/e2e/guest_test.go
  scheduler/test/testdata.go
Labels: kind/feature, approved, lgtm, cncf-cla: yes, size/L
