Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2023-12, with the labels that each got.

#85 fix Makefile bug
  Makefile
Labels: kind/bug, approved, lgtm, size/XS, cncf-cla: yes

#86 fix: use correct guest in binding cycles
  scheduler/plugin/export_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
Labels: kind/bug, approved, lgtm, size/M, cncf-cla: yes

#87 nit: change cyclestate's message
  guest/testdata/cyclestate/main.go
  guest/testdata/cyclestate/main.wasm
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#82 Support Reserve plugin
  Makefile
  guest/api/types.go
  guest/plugin/plugin.go
  guest/reserve/reserve.go
  guest/testdata/cyclestate/main.go
  guest/testdata/cyclestate/main.wasm
  guest/testdata/reserve/main.go
  guest/testdata/reserve/main.wasm
  internal/e2e/e2e.go
  internal/e2e/scheduler_perf/scheduler_perf_test.go
  scheduler/go.mod
  scheduler/plugin/guest.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
  scheduler/test/testdata/error/panic_on_reserve.wasm
  scheduler/test/testdata/error/panic_on_reserve.wat
  scheduler/test/testdata/test/reserve_from_global.wasm
  scheduler/test/testdata/test/reserve_from_global.wat
Labels: kind/feature, approved, kind/api-change, lgtm, cncf-cla: yes, size/L
