Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2024-02, with the labels that each got.

#102 chore: wazero v1.6.0 version bump
  internal/e2e/go.mod
  internal/e2e/go.sum
  scheduler/go.mod
  scheduler/go.sum
Labels: kind/feature, size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#104 remove unnecessary code
  scheduler/plugin/plugin_test.go
Labels: kind/bug, approved, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#103 set up cloudbuild
  cloudbuild.yaml
  scheduler/Dockerfile
Labels: kind/feature, approved, lgtm, size/M, cncf-cla: yes
