Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2024-11, with the labels that each got.

#125 Only start the extender plugin when needed in scheduler-perf
  internal/e2e/scheduler_perf/scheduler_perf_test.go
Labels: approved, lgtm, size/XS, cncf-cla: yes, kind/cleanup

#126 Upgrade `golangci-lint` to 1.61.0
  .github/workflows/commit.yaml
  .github/workflows/testdata.yaml
  Makefile
  scheduler/test/util.go
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#127 Improve benchmark performance of nodenumber wasm plugin
  Makefile
  internal/e2e/go.mod
  internal/e2e/go.sum
  internal/e2e/scheduler_perf/config/sched-config-all-enabled.yaml
  internal/e2e/scheduler_perf/wasm/nodenumber/main.go
  internal/e2e/scheduler_perf/wasm/nodenumber/main.wasm
Labels: size/S, approved, lgtm, cncf-cla: yes, kind/cleanup

#130 Fix Docker image building
  scheduler/Dockerfile
Labels: kind/bug, approved, lgtm, size/XS, cncf-cla: yes

#132 fix nodenumber plugin to use Pod name instead of pod.spec.nodeName
  examples/nodenumber/main.go
  examples/nodenumber/main_test.go
  internal/e2e/scheduler_perf/wasm/nodenumber/main.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes
