Repository kubernetes-sigs/kube-scheduler-wasm-extension, pull requests merged in 2024-01, with the labels that each got.

#83 Support EventRecorder
  examples/advanced/main.go
  examples/advanced/main.wasm
  examples/advanced/plugin/plugin.go
  examples/advanced/plugin/plugin_test.go
  examples/nodenumber/main.go
  examples/nodenumber/main.wasm
  examples/nodenumber/main_test.go
  guest/api/proto/proto.go
  guest/eventrecorder/api/eventrecorder.go
  guest/eventrecorder/api/eventrecorder_test.go
  guest/eventrecorder/eventrecorder.go
  guest/eventrecorder/eventrecorder_test.go
  guest/eventrecorder/imports.go
  guest/eventrecorder/imports_stub.go
  guest/eventrecorder/internal/eventrecorder.go
  guest/eventrecorder/internal/eventrecorder_test.go
  guest/filter/filter.go
  guest/internal/prefilter/types.go
  guest/internal/proto/proto.go
  guest/klog/api/k8s_references_test.go
  guest/klog/internal/klog_test.go
  guest/testdata/bind/main.wasm
  guest/testdata/cyclestate/main.wasm
  guest/testdata/filter/main.wasm
  guest/testdata/reserve/main.wasm
  guest/testdata/score/main.wasm
  internal/e2e/guest/guest_test.go
  internal/e2e/profiler/profiler.go
  internal/e2e/scheduler/scheduler_test.go
  scheduler/go.mod
  scheduler/plugin/host.go
  scheduler/plugin/host_test.go
  scheduler/plugin/plugin.go
  scheduler/plugin/plugin_test.go
  scheduler/plugin/runtime.go
  scheduler/test/util.go
Labels: kind/feature, approved, kind/api-change, lgtm, tide/merge-method-squash, cncf-cla: yes, size/XL

#96 doc: enrich the document for /examples
  README.md
  examples/README.md
Labels: size/S, approved, kind/documentation, lgtm, cncf-cla: yes

#99 Fix minor bug about %v
  scheduler/plugin/plugin_test.go
Labels: kind/bug, size/S, approved, lgtm, cncf-cla: yes

#100 doc: add a simple tutorial to guide users
  README.md
  docs/tutorial.md
  examples/README.md
Labels: approved, kind/documentation, lgtm, size/M, cncf-cla: yes

#98 Support RejectWaitingPod
  Makefile
  examples/advanced/main.go
  examples/advanced/main.wasm
  examples/advanced/plugin/plugin.go
  examples/advanced/plugin/plugin_test.go
  examples/nodenumber/main.go
  examples/nodenumber/main.wasm
  guest/handle/eventrecorder/api/eventrecorder.go
  guest/handle/eventrecorder/api/eventrecorder_test.go
  guest/handle/eventrecorder/eventrecorder.go
  guest/handle/eventrecorder/eventrecorder_test.go
  guest/handle/eventrecorder/imports.go
  guest/handle/eventrecorder/imports_stub.go
  guest/handle/eventrecorder/internal/eventrecorder.go
  guest/handle/eventrecorder/internal/eventrecorder_test.go
  guest/handle/handle.go
  guest/handle/imports.go
  guest/handle/imports_stub.go
  guest/internal/mem/mem.go
  guest/testdata/handle/main.go
  guest/testdata/handle/main.wasm
  scheduler/plugin/host.go
  scheduler/plugin/host_test.go
  scheduler/plugin/mem.go
  scheduler/plugin/plugin_test.go
  scheduler/test/testdata.go
  scheduler/test/util.go
Labels: kind/feature, approved, kind/api-change, lgtm, tide/merge-method-squash, cncf-cla: yes, size/L
